### ISSUE TITLE
Travis: add build

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/consul-config-loader#2]
I can't PR right now. That's why I open ticket :-)
The `.travis.yml` file should be very simple:

``` yaml
os:
  - linux
services:
  - docker
install:
  - docker build -t jhipster/consul-config-loader:travis .
script:
  - docker images
```
